# Generated by Django 4.2.5 on 2023-10-24 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_modified_at_filmwork_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmwork",
            name="certificate",
        ),
    ]
